FROM ubuntu:20.04

ARG USER

RUN DEBIAN_FRONTEND=noninteractive TZ=Asia/Shanghai \
    apt-get update && \
    apt-get install -y tzdata

RUN apt-get update && \
    apt-get install -y \
    sudo openssl openjdk-8-jdk perl libxml-simple-perl \
    git-core gnupg flex bison build-essential zip curl zlib1g-dev \
    gcc-multilib g++-multilib libc6-dev-i386 libncurses5-dev lib32ncurses5-dev \
    x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils \
    xsltproc unzip fontconfig

RUN apt-get update && \
    apt-get install -y \
    python2 python3

RUN update-alternatives --install /usr/bin/python python /usr/bin/python2 1
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 2

RUN useradd -m -p `openssl passwd -1 -salt 'salt' admin` ${USER} && usermod -a -G sudo ${USER}
