FROM ubuntu:16.04

ARG USER

RUN apt-get update && \
    apt-get install -y \
    sudo openssl openjdk-8-jdk perl libxml-simple-perl \
    git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev \
    gcc-multilib g++-multilib libc6-dev-i386 libncurses5-dev lib32ncurses5-dev \
    x11proto-core-dev libx11-dev lib32z-dev libgl1-mesa-dev libxml2-utils \
    xsltproc unzip

RUN useradd -m -p `openssl passwd -1 -salt 'salt' admin` ${USER} && usermod -a -G sudo ${USER}
