FROM ubuntu:20.04

ARG USER

RUN DEBIAN_FRONTEND=noninteractive TZ=Asia/Shanghai \
    apt-get update && \
    apt-get install -y tzdata

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
    sudo openssl openjdk-8-jdk perl libxml-simple-perl \
    rsync util-linux uuid-dev \
    git-core gnupg flex bison build-essential zip curl zlib1g-dev \
    libc6-dev-i386 libncurses5 lib32ncurses5-dev x11proto-core-dev \
    libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc \
    unzip fontconfig cmake cpio libssl-dev

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
    gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

RUN apt-get update && \
    apt-get install -y \
    python2 python3

RUN apt autoremove -y

RUN update-alternatives --install /usr/bin/python python /usr/bin/python2 1
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 2

RUN useradd -m -p `openssl passwd -1 -salt 'salt' admin` ${USER} && usermod -a -G sudo ${USER}
